name: Build and deploy Node.js app to Azure Web App - cliniplus-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_APP_URL: https://cliniplus-app.azurewebsites.net

      - name: Zip artifact for deployment
        run: |
          cp -r .next/standalone ./deploy
          cp -r .next/static ./deploy/.next/static
          cp -r public ./deploy/public
          cp -r prisma ./deploy/prisma
          cd deploy && zip -r ../release.zip . && cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d release

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: df5ee52f-9e3e-4815-817c-f1f34aeb0d92
          tenant-id: 0ec4b109-2bdb-4d88-9f9a-fc697e83b65b
          subscription-id: 287cb8fb-a658-4e09-8810-e159070f861f

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cliniplus-app'
          package: release
          startup-command: 'node server.js'
